---
- name: Ubuntu Server, debug environment
  hosts: testing
  roles:
    - role: ubuntu/neovim
    - role: ubuntu/apache

- name: Ubuntu Server, production
  hosts: production
  roles:
    - role: ubuntu/apache

